/* eslint-disable */
// Generated from docs/openapi/rend-public-api.openapi.json by scripts/generate-openapi-client.mjs.
// Do not edit this file directly. Run `bun run openapi:generate` instead.

export type AssetId = string;

export type BinaryUploadBody = string;

export type UploadId = string;

export type MultipartUploadStatus = "uploading" | "completing" | "completed" | "aborted" | "expired" | "failed";

export type CreateMultipartUploadRequest = {
  content_type: string;
  content_length: number;
  filename?: string;
};

export type MultipartUploadChecksum = string;

export type MultipartUploadPartNumber = number;

export type MultipartUploadCompletedPart = {
  part_number: MultipartUploadPartNumber;
  etag: string;
  checksum_sha256: MultipartUploadChecksum;
};

export type MultipartUploadStoredPart = {
  part_number: MultipartUploadPartNumber;
  etag: string;
  checksum_sha256?: MultipartUploadChecksum | null;
  size: number;
};

export type MultipartUploadSession = {
  asset_id: AssetId;
  upload_id: UploadId;
  part_size: number;
  part_count: number;
  max_parallel_parts: 6;
  expires_at: IsoTimestamp;
  status: MultipartUploadStatus;
  uploaded_parts: Array<MultipartUploadStoredPart>;
};

export type SignMultipartUploadPartRequest = {
  part_number: MultipartUploadPartNumber;
  checksum_sha256: MultipartUploadChecksum;
};

export type SignMultipartUploadPartsRequest = {
  parts: Array<SignMultipartUploadPartRequest>;
};

export type PresignedMultipartUploadPart = {
  part_number: MultipartUploadPartNumber;
  url: string;
  method: "PUT";
  headers: Record<string, string>;
};

export type SignMultipartUploadPartsResponse = {
  upload_id: UploadId;
  parts: Array<PresignedMultipartUploadPart>;
};

export type CompleteMultipartUploadRequest = {
  parts: Array<MultipartUploadCompletedPart>;
};

export type AssetState = string;

export type IsoTimestamp = string;

export type AssetSummary = {
  asset_id: AssetId;
  source_state: AssetState;
  playable_state: AssetState;
  created_at: IsoTimestamp;
  updated_at: IsoTimestamp;
  source_byte_size?: number;
  duration_ms?: number;
  has_thumbnail?: boolean;
  artifact_count: number;
  suspended_at?: IsoTimestamp;
  suspension_reason?: string;
  organization_suspended_at?: IsoTimestamp;
  organization_suspension_reason?: string;
};

export type AssetUploadResponse = {
  asset_id: AssetId;
  source_state: AssetState;
  playable_state: AssetState;
  byte_size: number;
  [key: string]: unknown;
};

export type AssetArtifact = {
  kind: string;
  content_type: string;
  byte_size?: number;
};

export type AssetDetail = {
  asset_id: AssetId;
  source_state: AssetState;
  playable_state: AssetState;
  created_at: IsoTimestamp;
  updated_at: IsoTimestamp;
  source_byte_size?: number;
  suspended_at?: IsoTimestamp;
  suspension_reason?: string;
  organization_suspended_at?: IsoTimestamp;
  organization_suspension_reason?: string;
  artifacts: Array<AssetArtifact>;
};

export type AssetListResponse = {
  assets: Array<AssetSummary>;
};

export type AssetDeleteResponse = {
  asset_id: AssetId;
  deleted: true;
  already_deleted: boolean;
  origin_objects_deleted: number;
  purge_attempted: boolean;
};

export type AssetEvent = {
  id: string;
  asset_id: AssetId;
  sequence: number;
  event_type: string;
  created_at: IsoTimestamp;
  metadata: Record<string, unknown>;
};

export type AssetEventsResponse = {
  asset_id: AssetId;
  events: Array<AssetEvent>;
  next_after_sequence?: number;
};

export type PlaybackArtifactPath = string;

export type PlaybackPrefetchHint = {
  artifact_path: PlaybackArtifactPath;
  url: string;
  content_type: string;
};

export type PlaybackBootstrapResponse = {
  status: "ready";
  asset_id: AssetId;
  source_state: AssetState;
  playable_state: AssetState;
  playback_url?: string;
  playback_content_type?: string;
  playback_credential_mode?: "include" | "omit";
  playback_token_expires_at: number;
  ttl_seconds: number;
  opener_url?: string;
  opener_content_type?: string;
  manifest_url?: string;
  manifest_content_type?: string;
  prefetch_hints: Array<PlaybackPrefetchHint>;
};

export type PlaybackUnavailableResponse = {
  status: "unavailable";
  asset_id: string;
  message: string;
};

export type PlaybackNotPlayableResponse = {
  status: "not_playable";
  asset_id: AssetId;
  source_state?: AssetState;
  playable_state?: AssetState;
  message: string;
};

export type PlaybackAnalyticsResponse = {
  asset_id: AssetId;
  window_started_at: IsoTimestamp;
  window_ended_at: IsoTimestamp;
  request_count: number;
  bytes_served: number;
  cache_status_counts: Record<string, number>;
  status_code_counts: Record<string, number>;
  first_seen?: IsoTimestamp;
  last_seen?: IsoTimestamp;
};

export type PlayerTelemetryPhase = "player_load" | "bootstrap_complete" | "source_selected" | "source_handoff" | "hls_ready" | "hls_level_switch" | "hls_fragment_loaded" | "metadata_loaded" | "canplay" | "first_frame" | "stall_start" | "stall_end" | "watch_heartbeat" | "bootstrap_failure" | "playback_failure" | "playback_ended";

export type PlayerTelemetryEvent = {
  playback_session_id: string;
  asset_id: string;
  phase: PlayerTelemetryPhase;
  event_time_ms: number;
  bootstrap_duration_ms?: number;
  bootstrap_http_status?: number;
  selected_playback_mode?: "native_hls" | "hls_js" | "opener" | "primary";
  selected_artifact_path?: PlaybackArtifactPath;
  previous_playback_mode?: "native_hls" | "hls_js" | "opener" | "primary";
  previous_artifact_path?: PlaybackArtifactPath;
  selected_width?: number;
  selected_height?: number;
  selected_bitrate?: number;
  hls_level_index?: number;
  hls_fragment_index?: number;
  hls_fragment_duration_ms?: number;
  hls_fragment_load_ms?: number;
  stall_reason?: string;
  stall_start_ms?: number;
  stall_end_ms?: number;
  stall_duration_ms?: number;
  watch_delta_ms?: number;
  metadata_loaded_ms?: number;
  canplay_ms?: number;
  first_frame_ms?: number;
  playback_failure_reason?: string;
  playback_failure_code?: string;
  cache_headers?: Record<string, string>;
  edge_label?: string;
  region_label?: string;
  player_version?: string;
  app_version?: string;
  [key: string]: unknown;
};

export type PlayerTelemetryBatch = PlayerTelemetryEvent | Array<PlayerTelemetryEvent> | {
  events: Array<PlayerTelemetryEvent>;
};

export type PlayerTelemetryAccepted = {
  status: "ok";
  accepted: number;
};

export type ControlPlaneError = {
  error: string;
};

export type SiteError = {
  status: "error";
  asset_id?: string;
  error?: string;
  message: string;
};

export type TelemetryErrorResponse = {
  status: "error";
  error: string;
};

export type RendClientOptions = {
  apiKey?: string;
  apiBaseUrl?: string;
  siteBaseUrl?: string;
  fetch?: typeof fetch;
  headers?: HeadersInit;
};

export type RendRequestOptions = {
  signal?: AbortSignal;
  headers?: HeadersInit;
};

export type UploadAssetOptions = RendRequestOptions & {
  contentType?: string;
  contentLength?: number;
};

export type CreateMultipartUploadOptions = RendRequestOptions & {
  idempotencyKey: string;
};

export type ListAssetsOptions = RendRequestOptions & {
  limit?: number;
};

export type ListAssetEventsOptions = RendRequestOptions & {
  afterSequence?: number;
  limit?: number;
};

export type StreamAssetEventsOptions = RendRequestOptions & {
  afterSequence?: number;
  assetId?: string;
};

export type PlaybackBootstrapOptions = RendRequestOptions & {
  playbackBaseUrl?: string;
};

export type PlaybackAnalyticsOptions = RendRequestOptions & {
  windowSeconds?: number;
};

export type WaitForPlayableAssetOptions = RendRequestOptions & {
  intervalMs?: number;
  timeoutMs?: number;
};

type JsonRecord = Record<string, unknown>;
type RequestInitWithDuplex = RequestInit & { duplex?: "half" };

const DEFAULT_API_BASE_URL = "https://api.rend.so";
const DEFAULT_SITE_BASE_URL = "https://rend.so";
const OPERATION_PATHS = {
  "uploadAsset": "/v1/videos",
  "createMultipartUpload": "/v1/uploads",
  "getMultipartUpload": "/v1/uploads/{uploadId}",
  "abortMultipartUpload": "/v1/uploads/{uploadId}",
  "signMultipartUploadParts": "/v1/uploads/{uploadId}/parts",
  "completeMultipartUpload": "/v1/uploads/{uploadId}/complete",
  "listAssets": "/v1/assets",
  "getAsset": "/v1/assets/{assetId}",
  "deleteAsset": "/v1/assets/{assetId}",
  "listAssetEvents": "/v1/assets/{assetId}/events",
  "streamAssetEvents": "/v1/events",
  "getPlaybackBootstrap": "/api/player/{assetId}",
  "recordPlayerTelemetry": "/api/player/telemetry",
  "getPlaybackAnalytics": "/v1/assets/{assetId}/analytics/playback"
} as const;

export class RendApiError extends Error {
  status: number;
  body: unknown;

  constructor(status: number, body: unknown) {
    super(errorMessage(status, body));
    this.name = "RendApiError";
    this.status = status;
    this.body = body;
  }
}

export class RendClient {
  private readonly apiKey?: string;
  private readonly apiBaseUrl: string;
  private readonly siteBaseUrl: string;
  private readonly fetchImpl: typeof fetch;
  private readonly defaultHeaders: HeadersInit | undefined;

  constructor(options: RendClientOptions = {}) {
    this.apiKey = options.apiKey;
    this.apiBaseUrl = normalizeBaseUrl(options.apiBaseUrl ?? DEFAULT_API_BASE_URL);
    this.siteBaseUrl = normalizeBaseUrl(options.siteBaseUrl ?? DEFAULT_SITE_BASE_URL);
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    this.defaultHeaders = options.headers;

    if (!this.fetchImpl) {
      throw new Error("RendClient requires a fetch implementation");
    }
  }

  uploadAsset(body: BodyInit, options: UploadAssetOptions = {}) {
    const headers = new Headers(options.headers);
    headers.set("content-type", options.contentType ?? "application/octet-stream");
    if (options.contentLength !== undefined) {
      headers.set("content-length", String(Math.trunc(options.contentLength)));
    }

    return this.requestJson<AssetUploadResponse>("api", OPERATION_PATHS.uploadAsset, {
      method: "POST",
      body,
      duplex: "half",
      headers,
      signal: options.signal
    });
  }

  createMultipartUpload(
    payload: CreateMultipartUploadRequest,
    options: CreateMultipartUploadOptions
  ) {
    const headers = new Headers(options.headers);
    headers.set("content-type", "application/json");
    headers.set("idempotency-key", options.idempotencyKey);
    return this.requestJson<MultipartUploadSession>(
      "api",
      OPERATION_PATHS.createMultipartUpload,
      {
        method: "POST",
        body: JSON.stringify(payload),
        headers,
        signal: options.signal
      }
    );
  }

  getMultipartUpload(uploadId: string, options: RendRequestOptions = {}) {
    return this.requestJson<MultipartUploadSession>(
      "api",
      pathParameter(OPERATION_PATHS.getMultipartUpload, "uploadId", uploadId),
      { method: "GET", headers: options.headers, signal: options.signal }
    );
  }

  signMultipartUploadParts(
    uploadId: string,
    payload: SignMultipartUploadPartsRequest,
    options: RendRequestOptions = {}
  ) {
    const headers = new Headers(options.headers);
    headers.set("content-type", "application/json");
    return this.requestJson<SignMultipartUploadPartsResponse>(
      "api",
      pathParameter(OPERATION_PATHS.signMultipartUploadParts, "uploadId", uploadId),
      {
        method: "POST",
        body: JSON.stringify(payload),
        headers,
        signal: options.signal
      }
    );
  }

  completeMultipartUpload(
    uploadId: string,
    payload: CompleteMultipartUploadRequest,
    options: RendRequestOptions = {}
  ) {
    const headers = new Headers(options.headers);
    headers.set("content-type", "application/json");
    return this.requestJson<MultipartUploadSession>(
      "api",
      pathParameter(OPERATION_PATHS.completeMultipartUpload, "uploadId", uploadId),
      {
        method: "POST",
        body: JSON.stringify(payload),
        headers,
        signal: options.signal
      }
    );
  }

  async abortMultipartUpload(uploadId: string, options: RendRequestOptions = {}) {
    await this.requestRaw(
      "api",
      pathParameter(OPERATION_PATHS.abortMultipartUpload, "uploadId", uploadId),
      { method: "DELETE", headers: options.headers, signal: options.signal }
    );
  }

  listAssets(options: ListAssetsOptions = {}) {
    return this.requestJson<AssetListResponse>(
      "api",
      OPERATION_PATHS.listAssets,
      { method: "GET", headers: options.headers, signal: options.signal },
      { limit: options.limit }
    );
  }

  getAsset(assetId: string, options: RendRequestOptions = {}) {
    return this.requestJson<AssetDetail>("api", assetPath(OPERATION_PATHS.getAsset, assetId), {
      method: "GET",
      headers: options.headers,
      signal: options.signal
    });
  }

  deleteAsset(assetId: string, options: RendRequestOptions = {}) {
    return this.requestJson<AssetDeleteResponse>("api", assetPath(OPERATION_PATHS.deleteAsset, assetId), {
      method: "DELETE",
      headers: options.headers,
      signal: options.signal
    });
  }

  listAssetEvents(assetId: string, options: ListAssetEventsOptions = {}) {
    return this.requestJson<AssetEventsResponse>(
      "api",
      assetPath(OPERATION_PATHS.listAssetEvents, assetId),
      { method: "GET", headers: options.headers, signal: options.signal },
      { after_sequence: options.afterSequence, limit: options.limit }
    );
  }

  async *streamAssetEvents(options: StreamAssetEventsOptions = {}): AsyncGenerator<AssetEvent> {
    const response = await this.requestRaw(
      "api",
      OPERATION_PATHS.streamAssetEvents,
      {
        method: "GET",
        headers: options.headers,
        signal: options.signal
      },
      { after_sequence: options.afterSequence, asset_id: options.assetId }
    );

    if (!response.body) return;

    const decoder = new TextDecoder();
    const reader = response.body.getReader();
    let buffer = "";

    while (true) {
      const chunk = await reader.read();
      if (chunk.done) break;
      buffer += decoder.decode(chunk.value, { stream: true });

      let boundary = buffer.indexOf("\n\n");
      while (boundary >= 0) {
        const frame = buffer.slice(0, boundary);
        buffer = buffer.slice(boundary + 2);
        const event = assetEventFromSseFrame(frame);
        if (event) yield event;
        boundary = buffer.indexOf("\n\n");
      }
    }

    buffer += decoder.decode();
    const event = assetEventFromSseFrame(buffer);
    if (event) yield event;
  }

  getPlaybackBootstrap(assetId: string, options: PlaybackBootstrapOptions = {}) {
    return this.requestJson<PlaybackBootstrapResponse>(
      "site",
      assetPath(OPERATION_PATHS.getPlaybackBootstrap, assetId),
      { method: "GET", headers: options.headers, signal: options.signal },
      { playbackBaseUrl: options.playbackBaseUrl }
    );
  }

  recordPlayerTelemetry(payload: PlayerTelemetryBatch, options: RendRequestOptions = {}) {
    const headers = new Headers(options.headers);
    headers.set("content-type", "application/json");

    return this.requestJson<PlayerTelemetryAccepted>("site", OPERATION_PATHS.recordPlayerTelemetry, {
      method: "POST",
      body: JSON.stringify(payload),
      headers,
      signal: options.signal
    });
  }

  getPlaybackAnalytics(assetId: string, options: PlaybackAnalyticsOptions = {}) {
    return this.requestJson<PlaybackAnalyticsResponse>(
      "api",
      assetPath(OPERATION_PATHS.getPlaybackAnalytics, assetId),
      { method: "GET", headers: options.headers, signal: options.signal },
      { window_seconds: options.windowSeconds }
    );
  }

  async waitForPlayableAsset(assetId: string, options: WaitForPlayableAssetOptions = {}) {
    const timeoutMs = options.timeoutMs ?? 120_000;
    const intervalMs = options.intervalMs ?? 1_000;
    const started = Date.now();

    while (true) {
      if (options.signal?.aborted) throw new Error("waitForPlayableAsset aborted");
      const asset = await this.getAsset(assetId, options);
      if (asset.playable_state === "opener_ready" || asset.playable_state === "hls_ready") {
        return asset;
      }
      if (asset.playable_state === "failed" || asset.playable_state === "deleted") {
        throw new Error(`asset ${assetId} reached terminal state ${asset.playable_state}`);
      }
      if (Date.now() - started >= timeoutMs) {
        throw new Error(`timed out waiting for asset ${assetId} to become playable`);
      }
      await sleep(intervalMs);
    }
  }

  private async requestRaw(
    server: "api" | "site",
    requestPath: string,
    init: RequestInitWithDuplex,
    query?: Record<string, string | number | boolean | undefined>
  ) {
    const headers = this.headers(server, init.headers);
    const response = await this.fetchImpl(this.url(server, requestPath, query), {
      ...init,
      headers
    });
    if (!response.ok) {
      throw new RendApiError(response.status, await readResponseBody(response));
    }
    return response;
  }

  private async requestJson<T>(
    server: "api" | "site",
    requestPath: string,
    init: RequestInitWithDuplex,
    query?: Record<string, string | number | boolean | undefined>
  ): Promise<T> {
    const response = await this.requestRaw(server, requestPath, init, query);
    return (await readResponseBody(response)) as T;
  }

  private headers(server: "api" | "site", input?: HeadersInit) {
    const headers = new Headers(this.defaultHeaders);
    for (const [key, value] of new Headers(input)) headers.set(key, value);
    if (server === "api" && this.apiKey && !headers.has("authorization")) {
      headers.set("authorization", `Bearer ${this.apiKey}`);
    }
    if (!headers.has("accept")) headers.set("accept", "application/json");
    return headers;
  }

  private url(
    server: "api" | "site",
    requestPath: string,
    query?: Record<string, string | number | boolean | undefined>
  ) {
    const baseUrl = server === "api" ? this.apiBaseUrl : this.siteBaseUrl;
    const url = new URL(requestPath, baseUrl);
    for (const [key, value] of Object.entries(query ?? {})) {
      if (value !== undefined) url.searchParams.set(key, String(value));
    }
    return url;
  }
}

function assetPath(template: string, assetId: string) {
  return pathParameter(template, "assetId", assetId);
}

function pathParameter(template: string, name: string, value: string) {
  return template.replace(`{${name}}`, encodeURIComponent(value));
}

function normalizeBaseUrl(value: string) {
  return value.endsWith("/") ? value : `${value}/`;
}

async function readResponseBody(response: Response): Promise<unknown> {
  const text = await response.text();
  if (!text) return undefined;
  const contentType = response.headers.get("content-type") ?? "";
  if (contentType.includes("application/json")) return JSON.parse(text);
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

function errorMessage(status: number, body: unknown) {
  if (isRecord(body)) {
    const message = body.message ?? body.error;
    if (typeof message === "string" && message.trim()) return message;
  }
  return `Rend API request failed with HTTP ${status}`;
}

function isRecord(value: unknown): value is JsonRecord {
  return Boolean(value && typeof value === "object" && !Array.isArray(value));
}

function assetEventFromSseFrame(frame: string): AssetEvent | null {
  const data = frame
    .split(/\r?\n/)
    .filter((line) => line.startsWith("data:"))
    .map((line) => line.slice("data:".length).trimStart())
    .join("\n");
  if (!data) return null;
  return JSON.parse(data) as AssetEvent;
}

function sleep(ms: number) {
  return new Promise<void>((resolve) => setTimeout(resolve, ms));
}
